---
title: "Quizzes and Exams"
---

Review materials for quizzes and exams will be posted here.

+---------+-------------------------------------------------------------+---------------+
| Type    | Description/Review Materials                                | Date          |
+=========+=============================================================+===============+
| Quiz    | Sample Quiz: [pdf](exams/q1/sample_quiz.pdf)                | 2018-09-24    |
+---------+-------------------------------------------------------------+---------------+
| Quiz    | Sample Quiz: [pdf](exams/q2/sample_quiz.pdf)                | 2018-10-01    |
|         | Sample Solutions: [pdf](exams/q2/sample_quiz_solutions.pdf) |               |
+---------+-------------------------------------------------------------+---------------+
| Midterm | Covers material from Homework 1 through Homework 5.         | 2018-10-10    |
|         | Topics include (but are not necessarily limited to):        |               |
|         | Observational units; variable types; plots; joint, marginal,| through       |
|         | and conditional distributions; independence; mean, median,  |               |
|         | quartiles/quantiles/percentiles, IQR, standard deviation;   | 2018-10-12    |
|         | correlation; sampling schemes; bias; experimental design;   |               |
|         | confounding.                                                |               |
|         |                                                             |               |
|         | Take-home portion on Gryd, distributed Wed 2018-10-10 and   |               |
|         | due on Fri 2018-10-12.  Take-home portion is similar to     |               |
|         | homework assignments in terms of working with data in R to  |               |
|         | make plots and calculate data summaries, but shorter.       |               |
|         | Limited interpretation or discussion of meaning.            |               |
|         |                                                             |               |
|         | In-class portion on Fri 2018-10-12.  In-class portion is    |               |
|         | similar to quizzes.  You will be given R output and asked   |               |
|         | to interpret it or use it for further calculations (like    |               |
|         | finding joint/marginal/conditional distributions).          |               |
|         | You may bring 1 double-sided 8.5 by 11 inch sheet of paper  |               |
|         | with notes on it to the in-class portion.                   |               |
+---------+-------------------------------------------------------------+---------------+
| Quiz    | Sample Quiz: [pdf](exams/q3/sample_quiz3.pdf)               | 2018-10-29    |
|         | Sample Solutions: [pdf](exams/q3/sample_quiz3_sol.pdf)      |               |
+---------+-------------------------------------------------------------+---------------+
| Midterm | Covers material from homework assignments 6 and 7.          | 2018-11-19    |
|         | You may bring 2 double-sided 8.5 by 11 inch sheets of paper |               |
|         | with notes to the in-class portion.                         |               |
|         | **Please also bring a calculator.**                         |               |
|         |                                                             |               |
|         | Sample Exam:                                                |               |
|         | [pdf](exams/exam02/practice02/practice_exam02.pdf)          |               |
|         |                                                             |               |
|         | Sample Exam Solutions:                                      |               |
|         | [pdf](exams/exam02/practice02/practice_exam02_sol.pdf)      |               |
+---------+-------------------------------------------------------------+---------------+
