---
title: "Introduction to Statistics"
---

**Instructor:** Evan Ray

**Email:** eray@mtholyoke.edu

**Office:** Clapp 404C

**Office Hours:** Regularly scheduled office hours at the following times: Mondays and Thursdays, 4pm-5pm; Wednesdays and Fridays, 3pm-4pm.  These are times I guarantee I will be in my office and available, but I am also willing to meet at other times we schedule! Please do not hesitate to contact me to set up appointments for additional office hours at any time!!

**Evening Group Work**: We have scheduled rooms for evening group work, with TAs available to help with questions, on the following days:

 * Tuesdays, 7:30 - 9:30 pm in Clapp 420
 * Thursdays, 7 - 9 pm in Clapp 401

**Piazza:** We have a Piazza page at [https://piazza.com/mtholyoke/fall2018/stat14002](https://piazza.com/mtholyoke/fall2018/stat14002).  You can ask and answer questions there, anonymously if you want, and everyone in the class will be able to see and contribute to the answers.

**Syllabus:** [pdf](syllabus/syllabus_stat_140.pdf)

Please use the navigation menu above to go to the schedule, homework assignments, and materials related to quizzes and exams.
