---
title: "Schedule"
---

**Click on the text like "Week 1: Sep 5 -- 7" to expand or collapse the items we covered in that week.**

I will fill in more detail and provide links to lecture notes and labs as we go along.  Items for future dates are tentative and subject to change.

```{r, echo = FALSE}
make_week_box <- function(id, open, title, contents) {
  cat('
<div class="panel panel-default">
<div class="panel-heading" role="tab" id="headingOne">
<h5 class="mb-0">
<a data-toggle="collapse" href="#',
id,
'" aria-expanded="true" aria-controls="collapseOne">
',
title,
'</a>
</h5>
</div>

<div id="',
id,
'" class="collapse',
ifelse(open, " in", ""),
'">
<div class="panel-body">
',
contents,
'
</div>
</div>
</div>',
  sep = "")
}
```

```{r, echo = FALSE, results='asis'}
make_week_box("week1", FALSE, "Week 1: Sep 5 -- 7",
"Chapter 1: Observational Units, Categorical and Quantitative Variables

#### Wed, Sept 5

 * **In class**, we will work on:
    * Introductory lab: [pdf](materials/20180904_intro/20180904Intro.pdf)
    * Here's a link to sign up for our class at gryd.us (this is the site where we will use R, you will need to do this to complete the lab): [https://beta.gryd.us/course/3wwAgQ39gQHjApaijRcWTE/register/](https://beta.gryd.us/course/3wwAgQ39gQHjApaijRcWTE/register/)
        * **Important**: Please use your mtholyoke.edu email address to register for this site!  Otherwise you will have to pay... :(
 * **After class**, please do the following:
    * **Fill out** a brief pre-course [questionairre](https://goo.gl/forms/JVuTZVSfee0tZ93O2)
    * **Fill out** this poll about when my office hours should be held: [http://whenisgood.net/d8wmb4z](http://whenisgood.net/d8wmb4z)
    * Sign up for our class at gryd.us if you didn't already (this is the site where we will use R): [https://beta.gryd.us/course/3wwAgQ39gQHjApaijRcWTE/register/](https://beta.gryd.us/course/3wwAgQ39gQHjApaijRcWTE/register/)
    * Sign up for our class at Piazza (anonymous question and answer forum): [https://piazza.com/mtholyoke/fall2018/stat14002](https://piazza.com/mtholyoke/fall2018/stat14002)
    * **Reading**: Read Chapter 1 of Stats: Data and Models 4th edition, or Chapter 2 of the 3rd edition
    * **Homework 1**: Complete 4 [DataCamp](https://www.datacamp.com) chapters from the Introduction to R course: Intro to basics, Vectors, Factors, and Data frames.  You will get an email by the end of the day on Sept 5 inviting you to join our class organization with an assignment pointing you to the specific chapters to do.  You should **feel free to work on this in groups** -- but please **each complete your own copy of this assignment**!  Your grade on this assignment is only for completion, not correctness.  If you get stuck, post a message on Piazza!  I don't expect you to remember everything or feel like an expert at it; that's what the rest of the class is for!  This is just a first introduction.

#### Fri, Sept 7

 * **In class**, we will work on:
    * Matching up ideas from the textbook and the data camp assignment.
    * Introduction to R and Categorical Data lab on Gryd.
 * **After class**, please do the following:
    * **Read**:
        * Stats: Data and Models 4th edition: Chapter 2, or
        * Stats: Data and Models 3rd edition: Chapter 3
    * Start on **Homework 2**: Data camp assignment about \"Introduction to the Tidyverse\", due Wednesday Sep 12.
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week2", FALSE, "Week 2: Sep 10 -- 14",
"

#### Mon, Sep 10
 * **In class**, we will work on:
    * Wrap-up of lab from Friday; things to know about R so far.  R Commands summary: [pdf](resources/data_loading_wrangling/data_loading_wrangling.pdf)
    * Material from Chapter 2 and related R functionality:
        * Example involving Joint, Marginal, and Conditional distributions based on a sample; Independence; and Simpson's Paradox.  [pdf](materials/20180910_categorical/20180910_categorical.pdf)
        * The `count` function in R
 * **After class**, please do the following:
    * **Read**:
        * Stats: Data and Models 4th edition: Chapters 3 and 4, or
        * Stats: Data and Models 3rd edition: Chapters 4 and 5
    * Finish **Homework 2**: Data camp assignment about \"Introduction to the Tidyverse\", due Wednesday Sep 12.

#### Wed, Sep 12
 * **In class**, we will work on:
    * Material from Chapters 3 and 4 and related R functionality:
        * Brief recap of data visualization with ggplot2: [pdf](resources/visualization/visualization.pdf)
        * Start on a lab about data visualizations and calculating quantitative summaries of data
 * **After class**, please do the following:
    * No new work outside of class.

#### Fri, Sep 14
 * **In class**, we will work on:
    * More about visualization:
        * Understanding and interpreting common types of plots: [pdf](materials/20180914_visualizations/20180914_visualizations.pdf)
        * Finish data visualizations part of lab 02
 * **After class**, please do the following:
    * Start on **Homework 3**: Assignment covering Chapters 1 -- 2 and data visualizations, on Gryd, due Wednesday Sep 19.
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week3", FALSE, "Week 3: Sep 17 -- 21",
"

#### Mon, Sep 17
 * **In class**, we will work on:
    * When to use mean/median, standard deviation/IQR. [pdf](materials/20180917_summaries/20180917_summaries.pdf)
    * R commands for dealing with quantitative variables. [pdf](materials/20180917_summaries/20180917_R_commands_quantitative.pdf)
    * Brief recap of all functionality related to reading in and summarizing data in R so far (see Resources tab)
    * Finish the whole Bechdel test lab; please submit by the end of the day today.
 * **After class**, please do the following:
    * **Homework 3**: Assignment covering Chapters 1 -- 2 and data visualizations, on Gryd, due Wednesday Sep 19.
    * **Read**:
        * Stats: Data and Models 4th edition: Sections 6.1 through 6.3 (but not the sections about Kendall’s Tau or Spearman’s Rho; also, we won't be calculating correlation by hand, so don't worry about those calculations - we will want to understand its properties and what it does and does not tell us), or
        * Stats: Data and Models 3rd edition: Chapter 7 (but not the sections about Kendall’s Tau, Spearman’s Rho, or Straightening Scatterplots; also, we won't be calculating correlation by hand, so don't worry about those calculations - we will want to understand its properties and what it does and does not tell us)

#### Wed, Sep 19
 * **Homework 3 due!**
 * **In class**, we will work on:
    * Material from Chapter 6 (4th edition); or Chapter 7 (3rd edition)
    * Thinking about the relationship between 2 quantitative variables: scatter plots and correlation [pdf](materials/20180919_scatterplots_correlation/20180919_correlation_summary.pdf)
    * Building some intuition about what correlation means: [pdf](materials/20180919_scatterplots_correlation/20180919_plots_correlation.pdf)
    * Lab03 on Gryd: practice working with scatter plots and correlation.
 * **After class**, please:
    * **Read**:
        * Stats: Data and Models 4th edition: Chapter 11
        * Stats: Data and Models 4th edition: Chapter 12

#### Fri, Sep 21
 * **In class**, we will work on:
    * Material from Chapter 11 (4th edition); or Chapter 12 (3rd edition)
    * Sampling Summary [pdf](materials/20180921_sampling/20180921_sampling_summary.pdf)
    * Lab04 on Gryd: Goldfish lab, introduction to sampling distributions and bias.
 * **After class**, please:
    * **Read**:
        * Stats: Data and Models 4th edition: Chapter 12
        * Stats: Data and Models 4th edition: Chapter 13
    * **Homework 4**: Assignment covering Chapters 3 -- 4 and 6, on Gryd, due Wednesday Sep 26 at midnight.
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week4", FALSE, "Week 4: Sep 24 -- 28",
"

#### Mon, Sep 24
 * **In class**, we will work on:
    * **Quiz** on material from HW03.  Solutions to HW03 are posted on Gryd and a sample quiz is posted on the [Quizzes/Exams](http://www.evanlray.com/stat140_f2018/exams.html) page on the course website.
    * Wrap up of Lab03 on Gryd, which we did on Friday Sep 21
    * Summary of Experiments and Observational Studies: [pdf](materials/20180924_observational_experiments/20180924_experiments_observational_summary.pdf)
    * Examples
        * Worksheet: [pdf](materials/20180924_observational_experiments/20180924_experiments_observational.pdf)
        * Solutions: [pdf](materials/20180924_observational_experiments/20180924_experiments_observational_solutions.pdf)
        * Study 1: [pdf](materials/20180924_observational_experiments/colds-and-meditation_Annals-Family-Medicine_12.pdf)
        * Study 2: [pdf](materials/20180924_observational_experiments/coffee-drinking-and-mortality_NEJM-12.pdf)
 * **After class**, please:
    * **Homework 4**: Assignment covering Chapters 3 -- 4 and 6, on Gryd, due Wednesday Sep 26 at midnight.

#### Wed, Sep 26
 * **Homework 4 due at midnight!**
 * **In class**, we will work on:
    * Introduction to hypothesis testing [pdf](materials/20180926_intro_testing/20180926_friend_or_foe.pdf)
 * **After class**, please:
    * **Homework 5** due Wednesday, Oct 3
    * **Read**
        * Stats: Data and Models 4th edition: Sections 16.1, 16.2, and 16.3.  Don't worry about the formulas, we will be using R for computations.
        * Stats: Data and Models 3rd edition: Chapter 17 - just the first few sections, up to and including \"The Binomial Model\"; stop before \"The Normal Model to the Rescue!\"  Don't worry about the formulas, we will be using R for computations.

#### Fri, Sep 28
 * **In class**, we will work on:
    * The binomial model and its use for hypothesis tests about a proportion.
        * UPDATED, CORRECT VERSION: [pdf](materials/20180928_rvs_binomial/20180928_binomial_corrected.pdf)
        * ORIGINAL, INCORRECT VERSION: [pdf](materials/20180928_rvs_binomial/20180928_binomial.pdf)
    * Lab 06 on Gryd
 * **After class**, please:
    * **Homework 5** due Wednesday, Oct 3
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week5", TRUE, "Week 5: Oct 1 -- 5",
"
More on inference for a population proportion.

#### Mon, Oct 1
 * **In class**, we will work on:
    * Quiz on material from HW4 (see Quizzes/Exams page for review materials)
    * Correction to discussion of `pbinom` from last class.
    * Wrap up Lab 06 on Gryd
    * More about hypothesis tests for a population proportion.
        * Worksheet: [pdf](materials/20181001_proportion_h_test/20181001_proportion_h_test.pdf)
        * Solutions: [pdf](materials/20181001_proportion_h_test/20181001_proportion_h_test_solutions.pdf)
 * **After class**, please:
    * **Homework 5** due Wednesday, Oct 3

#### Wed, Oct 3
 * **Homework 5 due today!!**
 * **In class**, we will work on:
    * Review of examples from last class
    * Lab 07 on Gryd: more examples of hypothesis tests about proportions, practice doing computations in R
 * **After class**, please:
    * Start reviewing for our first midterm

#### Fri, Oct 5
 * **In class**, we will work on:
    * Start thinking about confidence intervals for a population proportion
 * **After class**, please:
    * Review for our first midterm
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week6", FALSE, "Week 6: Oct 8 -- 12",
"

#### Mon, Oct 8
 * **No Class**: mid-semester break.  Safe travels!

#### Wed, Oct 10

#### Fri, Oct 12
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week7", FALSE, "Week 7: Oct 15 -- 19",
"

#### Mon, Oct 15

#### Wed, Oct 17

#### Fri, Oct 19
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week8", FALSE, "Week 8: Oct 22 -- 26",
"
#### Mon, Oct 22

#### Wed, Oct 24

#### Fri, Oct 26
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week9", FALSE, "Week 9: Oct 29 -- Nov 2",
"

#### Mon, Oct 29

#### Wed, Oct 31

#### Fri, Nov 2
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week10", FALSE, "Week 10: Nov 5 -- 9",
"

#### Mon, Nov 5

#### Wed, Nov 7

#### Fri, Nov 9
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week11", FALSE, "Week 11: Nov 12 -- 16",
"

#### Mon, Nov 12

#### Wed, Nov 14

#### Fri, Nov 16
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week12", FALSE, "Week 12: Nov 19 -- 23 (Thanksgiving)",
"

#### Mon, Nov 19

#### Wed, Nov 21
* **No Class**: Thanksgiving break.  Safe travels!

#### Fri, Nov 23
* **No Class**: Thanksgiving break.  Safe travels!
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week13", FALSE, "Week 13: Nov 26 -- 30",
"

#### Mon, Nov 26

#### Wed, Nov 28

#### Fri, Nov 30
"
)
```

```{r, echo = FALSE, results='asis'}
make_week_box("week14", FALSE, "Week 14: Dec 3 -- 7",
"

#### Mon, Dec 3

#### Wed, Dec 5

#### Fri, Dec 7
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week15", FALSE, "Week 15: Dec 10",
"

#### Mon, Dec 10
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("finals", TRUE, "Final Exams: Fri, Dec 14 at 7pm -- Tue, Dec 18 at noon",
"We will have a cumulative final exam.
"
  )
```
