---
title: "Experiments and Observational Studies"
output:
  pdf_document:
    fig_height: 2.8
    fig_width: 6
  html_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
documentclass: extarticle
classoption: 14pt
geometry: margin=0.6in
---

## Abstract 1

After reading the abstract of "Meditation or Exercise for Preventing Acute Respiratory Infection: A Randomized Controlled Trial", answer the following questions:

#### 1. Is this an observational study or an experiment?

\vspace{1.4cm}

#### 2. What are the explanatory and response variables?

\vspace{1.4cm}

#### 3. In what way was randomization used in the study?

\vspace{1.4cm}

#### 4. What were the treatments used in the study?

\vspace{1.4cm}

#### 5. What sources of bias might be present?

\vspace{1.4cm}

#### 6. Was there any evidence of blinding?

\vspace{1.4cm}

#### 7. What did the study conclude?

\newpage

## Abstract 2

After reading the abstract of "Association of Coffee Drinking with Total and Cause-Specific Mortality", answer the following questions:

#### 1. Is this an observational study or an experiment?

\vspace{2cm}

#### 2. Is the study prospective or retrospective?

\vspace{2cm}

#### 3. What are the explanatory and response variables?

\vspace{2cm}

#### 4. How did the authors adjust for possible sources of confounding?

\vspace{2cm}

#### 5. What did the study conclude?
